version: '3'
wordpress:
  image: wordpress:fpm
  links:
    - db:mysql
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: nadgroup@@9
services:
  app:
    image: raulr/nginx-wordpress
    links:
     - wordpress
    volumes_from:
     - wordpress
    expose:
      - "80"
    ports:
      - 8080:80
    environment:
      POST_MAX_SIZE: 128m