version: '3'
services:
  app:
    image: wordpress-nginx
    links:
     - db:mysql
    depends_on:
     - db
    volumes:
     - ./wordpress:/var/www/html
    expose:
      - "80"
    ports:
      - 8080:80
    environment:
      POST_MAX_SIZE: 128m
  db:
    image: mariadb
    environment:
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress@@9
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: nadgroup@@9