version: '3'
services:
  wordpress:
    image: wordpress:fpm
    links:
      - db:mysql
  app:
    image: raulr/nginx-wordpress
    links:
     - wordpress
    volumes_from:
     - wordpress
    expose:
      - "80"
    ports:
      - 8080:80
    environment:
      POST_MAX_SIZE: 128m
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nadgroup@@9