version: '3'
services:
  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    links:
      - db:mysql
    volumes:
      - blogsource:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpressdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=nadgroup@@9
    restart: always
  app:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - blogsource:/var/www/html
    links:
      - wordpress
    depends_on:
      - wordpress
    restart: always
    expose:
      - "80"
    ports:
      - "8080:80"
    environment:
      POST_MAX_SIZE: 128m
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nadgroup@@9
      MYSQL_DATABASE: wordpressdb
volumes:
    blogsource:
        external:
            name: ./wordpress