version: '3'
services:
  proxy:
    build: ./
    networks:
      - nadgroup
      - blog
    ports:
      - 80:80

networks:
  nadgroup:
    external:
      name: nadgroup_default
  blog:
    external:
      name: blog_default