version: '3'
services:
  proxy:
    build: ./
    networks:
      - site1
      - site2
    ports:
      - 80:80

  networks:
    site1:
      external:
        name: nadgroup_default
    site2:
      external:
        name: blog_default