version: '3'
services:
  proxy:
    build: ./
    networks:
      - nadgroup
      - nadgroupblog
    ports:
      - 80:80

  networks:
    nadgroup:
      external:
        name: nadgroup_default
    nadgroupblog:
      external:
        name: blog_default